-- 회원
CREATE TABLE `MEMBER` (
	`MEMBER_UID` INT          NOT NULL COMMENT '회원UID', -- 회원UID
	`ID`         VARCHAR(30)  NULL     COMMENT '아이디', -- 아이디
	`PASSWORD`   VARCHAR(128) NULL     COMMENT '암호', -- 암호
	`NAME`       VARCHAR(30)  NULL     COMMENT '이름' -- 이름
)
COMMENT '회원';

-- 회원
ALTER TABLE `MEMBER`
	ADD CONSTRAINT `PK_MEMBER` -- 회원 기본키
		PRIMARY KEY (
			`MEMBER_UID` -- 회원UID
		);

ALTER TABLE `MEMBER`
	MODIFY COLUMN `MEMBER_UID` INT NOT NULL AUTO_INCREMENT COMMENT '회원UID';

ALTER TABLE `MEMBER`
	AUTO_INCREMENT = 1;

-- 쿠폰그룹
CREATE TABLE `COUPON_GROUP` (
	`COUPON_GROUP_UID`  INT         NOT NULL COMMENT '쿠폰그룹UID', -- 쿠폰그룹UID
	`COUPON_GROUP_NAME` VARCHAR(30) NULL     COMMENT '쿠폰그룹명' -- 쿠폰그룹명
)
COMMENT '쿠폰그룹';

-- 쿠폰그룹
ALTER TABLE `COUPON_GROUP`
	ADD CONSTRAINT `PK_COUPON_GROUP` -- 쿠폰그룹 기본키
		PRIMARY KEY (
			`COUPON_GROUP_UID` -- 쿠폰그룹UID
		);

ALTER TABLE `COUPON_GROUP`
	MODIFY COLUMN `COUPON_GROUP_UID` INT NOT NULL AUTO_INCREMENT COMMENT '쿠폰그룹UID';

ALTER TABLE `COUPON_GROUP`
	AUTO_INCREMENT = 1;

-- 쿠폰
CREATE TABLE `COUPON` (
	`COUPON_CODE`      VARCHAR(19) NOT NULL COMMENT '쿠폰코드', -- 쿠폰코드
	`USE_DATETIME`     DATETIME    NULL     COMMENT '사용일시', -- 사용일시
	`IS_USE`           INT         NULL     COMMENT '사용여부', -- 사용여부
	`COUPON_GROUP_UID` INT         NULL     COMMENT '쿠폰그룹UID', -- 쿠폰그룹UID
	`MEMBER_UID`       INT         NULL     COMMENT '회원UID' -- 회원UID
)
COMMENT '쿠폰';

-- 쿠폰
ALTER TABLE `COUPON`
	ADD CONSTRAINT `PK_COUPON` -- 쿠폰 기본키
		PRIMARY KEY (
			`COUPON_CODE` -- 쿠폰코드
		);

-- 쿠폰
ALTER TABLE `COUPON`
	ADD CONSTRAINT `FK_COUPON_GROUP_TO_COUPON` -- 쿠폰그룹 -> 쿠폰
		FOREIGN KEY (
			`COUPON_GROUP_UID` -- 쿠폰그룹UID
		)
		REFERENCES `COUPON_GROUP` ( -- 쿠폰그룹
			`COUPON_GROUP_UID` -- 쿠폰그룹UID
		);

-- 쿠폰
ALTER TABLE `COUPON`
	ADD CONSTRAINT `FK_MEMBER_TO_COUPON` -- 회원 -> 쿠폰
		FOREIGN KEY (
			`MEMBER_UID` -- 회원UID
		)
		REFERENCES `MEMBER` ( -- 회원
			`MEMBER_UID` -- 회원UID
		);